---
name: Release

on:
  pull_request:
    types:
      - closed
    branches:    
      - main      

jobs:
  build:
    runs-on: ubuntu-latest  # this is just the host, but the job will run in the container
    container: ubuntu:20.04
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        # Install required dependencies inside the container
        apt-get update
        apt-get install -y python3 python3-pip python3-dev wget build-essential       
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use pyinstall to create ziti_router_auto_enroll distribution binary
      run: pyinstaller -F ziti_router_auto_enroll.py      

    - name: version
      run: echo "version=$(./dist/ziti_router_auto_enroll -v)" >> $GITHUB_ENV
      id: version
      
    - name: Tar ziti router auto enroll
      run: cd dist; tar -zcvf ziti_router_auto_enroll.tar.gz ziti_router_auto_enroll

    - name: release
      uses: ncipollo/release-action@v1
      id: release
      with:
        draft: false
        prerelease: false
        tag: v${{ env.version }}
        artifacts: dist/ziti_router_auto_enroll.tar.gz
        artifactContentType: application/gzip
      env:
        GITHUB_TOKEN: ${{ github.token }}
